name: talky
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  http: ^1.2.0
  permission_handler: ^12.0.1
  flutter_webrtc: ^1.3.0
  dart_webrtc: ^1.7.0
  socket_io_client: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true